import type { ReferencePattern } from "../types.ts";

export const referenceCatalog: ReferencePattern[] = [
  {
    id: "joan-ramos",
    name: "Joan Ramos Refusta",
    url: "https://github.com/jrefusta/joan-portfolio",
    category: "room",
    license: "MIT",
    reuse: "approved",
    similarity: 3,
    tags: ["room", "computer", "gallery", "games", "css3d", "baked-lighting"],
    patterns: [
      "Use a room as a semantic container instead of a decorative backdrop",
      "Turn monitors and arcade machines into deep interactive exhibits",
      "Bake lighting for visual quality while preserving browser performance",
    ],
  },
  {
    id: "sooah-room-folio",
    name: "Soo-ah’s Room Folio",
    url: "https://github.com/andrewwoan/sooahs-room-folio",
    category: "room",
    license: "MIT",
    reuse: "approved",
    similarity: 3,
    tags: ["room", "hotspots", "day-night", "music", "blender", "guided"],
    patterns: [
      "Use curated hotspots so visitors never have to guess what is interactive",
      "Let the visual theme respond to the profile’s personality",
      "Pair the 3D view with readable modal content",
    ],
  },
  {
    id: "andrii-babintsev",
    name: "Andrii Babintsev",
    category: "room",
    license: "MIT",
    reuse: "quarantined",
    similarity: 3,
    tags: ["office", "physics", "mini-games", "interactive-objects"],
    patterns: [
      "Distribute interaction across many small personal objects",
      "Use lightweight physics for memorable moments",
      "Give every room one clear interaction density budget",
    ],
  },
  {
    id: "maxime-morel",
    name: "Maxime Morel",
    url: "https://github.com/maxime-mrl/3D-room-portofolio",
    category: "room",
    license: "MIT",
    reuse: "approved",
    similarity: 3,
    tags: ["low-poly", "room", "hover", "click", "blender"],
    patterns: [
      "Prefer a coherent low-poly language over many mismatched high-detail assets",
      "Use hover feedback before click interactions",
      "Keep the first scene understandable from a single overview camera",
    ],
  },
  {
    id: "bruno-simon",
    name: "Bruno Simon 2025",
    url: "https://github.com/brunosimon/folio-2025",
    category: "world",
    license: "MIT",
    reuse: "approved",
    similarity: 3,
    tags: ["world", "vehicle", "physics", "onboarding", "quality", "recovery"],
    patterns: [
      "Teach controls inside the world instead of in a manual",
      "Offer quality modes and a recovery action",
      "Make navigation itself communicate personality",
    ],
  },
  {
    id: "henry-heffernan",
    name: "Henry Heffernan",
    url: "https://os.henryheffernan.com/",
    category: "retro",
    license: "MIT",
    reuse: "quarantined",
    similarity: 3,
    tags: ["retro", "computer", "doom", "oregon-trail", "operating-system"],
    patterns: [
      "Use a familiar computer metaphor for dense information",
      "Separate the serious portfolio from playful optional experiences",
      "Let one hero object become the navigation hub",
    ],
  },
  {
    id: "mingpv",
    name: "MingPV 3D Portfolio",
    category: "template",
    license: "Apache-2.0",
    reuse: "quarantined",
    similarity: 2,
    tags: ["nuxt", "template", "threejs", "customizable"],
    patterns: [
      "Keep profile data separate from scene implementation",
      "Expose theme tokens for rapid personalization",
      "Document the replacement path for every starter asset",
    ],
  },
  {
    id: "react18-portfolio",
    name: "React 18 3D Portfolio",
    url: "https://github.com/ladunjexa/reactjs18-3d-portfolio",
    category: "template",
    license: "MIT",
    reuse: "approved",
    similarity: 1,
    tags: ["react", "computer", "earth", "stars", "sections"],
    patterns: [
      "Keep conventional content sections as an accessibility fallback",
      "Lazy-load secondary canvases",
      "Use recognizable visual anchors for skills and contact information",
    ],
  },
  {
    id: "at-room",
    name: "AT010303 Room Portfolio",
    url: "https://github.com/AT010303/Room_Portfolio",
    category: "room",
    license: "No LICENSE",
    reuse: "research-only",
    similarity: 3,
    tags: ["room", "mario", "music", "theme", "interactive-objects"],
    patterns: [
      "Use theme switching to reveal a second emotional layer",
      "Let optional mini-experiences reward exploration",
      "Avoid putting every interaction in the critical path",
    ],
  },
  {
    id: "rowobin-room",
    name: "Rowobin 3D Room Portfolio",
    url: "https://github.com/Rowobin/3D-Room-Portfolio",
    category: "room",
    license: "No LICENSE",
    reuse: "research-only",
    similarity: 3,
    tags: ["room", "blender", "portfolio"],
    patterns: [
      "Build a recognizable room silhouette before adding small props",
      "Reserve empty space for overlays and camera framing",
      "Use object grouping that mirrors portfolio sections",
    ],
  },
  {
    id: "david-heckhoff",
    name: "David Heckhoff",
    category: "visual",
    license: "Custom non-commercial",
    reuse: "visual-only",
    similarity: 2,
    tags: ["vue", "glsl", "gsap", "cinematic"],
    patterns: [
      "Use restrained transitions to preserve visual hierarchy",
      "Let shaders reinforce a concept instead of acting as decoration",
      "Treat camera cuts as editorial decisions",
    ],
  },
  {
    id: "jesses-ramen",
    name: "Jesse’s Ramen",
    category: "visual",
    license: "Source not confirmed",
    reuse: "visual-only",
    similarity: 3,
    tags: ["cyberpunk", "shop", "narrative", "neon"],
    patterns: [
      "Use a place with a strong social identity as the portfolio shell",
      "Build narrative density with signage and environmental detail",
      "Keep a limited neon palette so content stays legible",
    ],
  },
  {
    id: "thibault-gamefolio",
    name: "Thibault Introvigne — Space Gamefolio",
    category: "visual",
    license: "Source not confirmed",
    reuse: "visual-only",
    similarity: 3,
    tags: ["space", "game", "career", "missions"],
    patterns: [
      "Translate career milestones into spatial missions",
      "Use a map to reveal progress and remaining content",
      "Keep playful navigation optional for time-constrained visitors",
    ],
  },
];

export const roomFirstReferenceIds = [
  "joan-ramos",
  "sooah-room-folio",
  "andrii-babintsev",
  "maxime-morel",
];
